"""Turn the digest data into an email: subject, plain text and a simple inline-styled HTML table layout.

Both renderers work from one small document (a list of blocks), so the text and the HTML always say the same thing.
Everything that goes into the HTML is escaped; the subject goes through ``clean_text``.
"""

from __future__ import annotations

import base64
import html as _html
import re
from datetime import datetime
from typing import Any

from .digest import WARN_TEXT, inr, num, num_intl, pct_text
from .notify import clean_text

FOOTER = "Generated by rules from public data; not financial advice. The agent places no orders from this email."
DELAYED = "(prices may be delayed)"
TONES = {"warn": "#b45309", "bad": "#b91c1c", "good": "#15803d", None: "#111827"}


def _plural(n: int, word: str) -> str:
    return f"{n} {word}" if n == 1 else f"{n} {word}s"


def subject(data: dict[str, Any]) -> str:
    if data["kind"] == "morning":
        mood = data.get("mood") or {}
        label = "market data unavailable" if "unavailable" in mood else str(mood.get("regime") or "unknown").replace("_", "-")
        ideas = data.get("buy_ideas") or {}
        n_buy = 0 if ("unavailable" in ideas or ideas.get("wait")) else len(ideas.get("ideas", []))
        watch = data.get("watch") or {}
        n_watch = 0 if "unavailable" in watch else watch.get("total", len(watch.get("items", [])))
        s = f"Today: {label} · {_plural(n_buy, 'buy idea')} · {n_watch} to watch"
    else:
        g, p = data.get("groww") or {}, data.get("practice") or {}
        stale = data.get("stale_close")
        if stale:   # no trading today / before the close: no "today" figures
            if "unavailable" not in g:
                s = f"Close ({stale['label']}): total {inr(g.get('pl'), 0, True)} ({pct_text(g.get('pl_pct'))})"
            elif "unavailable" not in p:
                s = f"Close ({stale['label']}): practice total {inr(p.get('total_pl'), 0, True)} ({pct_text(p.get('total_pl_pct'))})"
            else:
                s = f"Close ({stale['label']}): portfolio unavailable"
            return clean_text(s, 150)
        if "unavailable" not in g:
            day = (f"{inr(g.get('day_pl'), 0, True)} / {pct_text(g.get('day_pct'))} today"
                   if g.get("day_pl") is not None else "day change unavailable")
            s = f"Close: {day} · total {inr(g.get('pl'), 0, True)} ({pct_text(g.get('pl_pct'))})"
        elif "unavailable" not in p:
            day = (f"{inr(p.get('day_change'), 0, True)} / {pct_text(p.get('day_change_pct'))} today"
                   if p.get("day_change") is not None else "day change unavailable")
            s = f"Close: practice {day} · total {inr(p.get('total_pl'), 0, True)} ({pct_text(p.get('total_pl_pct'))})"
        else:
            s = "Close: portfolio unavailable"
    return clean_text(s, 150)


def _block(title: str | None, lines: list[str] | None = None, table: dict[str, Any] | None = None,
           tone: str | None = None, kv: list[tuple[str, str]] | None = None,
           cards: list[dict[str, Any]] | None = None, images: list[dict[str, str]] | None = None, cont: bool = False) -> dict[str, Any]:
    return {"title": title, "lines": lines or [], "table": table, "tone": tone, "kv": kv or [], "cards": cards,
            "images": images or [], "cont": cont}


def _unavail(title: str, sec: dict[str, Any]) -> dict[str, Any]:
    return _block(title, [f"Unavailable: {sec['unavailable']}"], tone="warn")


def _morning_blocks(d: dict[str, Any]) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []
    mood = d["mood"]
    if "unavailable" in mood:
        blocks.append(_unavail("Market mood", mood))
    else:
        # Regime and Nifty as a short key/value list; the other markets are in World markets and Risk gauges
        regime = str(mood.get("regime") or "unknown").replace("_", "-")
        kv = [("Regime", f"{regime}, score {mood['score']}, trend {mood.get('trend') or 'n/a'}"
               if isinstance(mood.get("score"), int) else regime)]
        nf = mood.get("nifty") or {}
        if nf.get("last") is not None:
            above = {True: "above its 200-day average", False: "below its 200-day average"}.get(nf.get("above_200dma"), "200-day average n/a")  # type: ignore[arg-type]
            kv.append(("Nifty", f"{num(nf['last'])}, {pct_text(nf.get('ret_1d_pct'))} today, "
                                f"{pct_text(nf.get('ret_20d_pct'))} in 20 days, {above}"))
        lines = [] if kv else [mood.get("summary") or regime]
        if mood.get("no_new_buys"):
            lines.insert(0, "No new buys today: " + " and ".join(mood.get("why") or ["the market filter says wait"]) + ".")
            lines.insert(1, "Rule: " + (mood.get("rules") or "the market filter") + ".")
        lines += [f"Note: {n}" for n in mood.get("notes", [])]
        blocks.append(_block("Market mood", lines, tone="bad" if mood.get("no_new_buys") else None, kv=kv))
    if "world" in d:
        blocks.append(_world_block(d["world"]))
    if "gauges" in d:
        blocks.append(_gauge_block(d["gauges"]))
    ideas = d["buy_ideas"]
    wait = (not ("unavailable" in mood)) and mood.get("no_new_buys")
    title = "Would pass, but the market filter says wait" if wait else "Buy ideas"
    if "unavailable" in ideas:
        blocks.append(_unavail(title, ideas))
    else:
        rows = [[i["symbol"], inr(i["price"], 2), str(i["qty"]), inr(i["notional"]), inr(i["stop"], 2) if i["stop"] else "n/a",
                 pct_text(i["ret_6m_pct"]), i["name"]] for i in ideas["ideas"]]
        pricey = ideas.get("too_expensive") or []
        lines = [f"Momentum screen of {ideas['universe']}: {ideas['scored']} of {ideas['universe_size']} scored, "
                 f"{ideas['eligible']} pass (above the 200-day average, liquid)"
                 + (f"; {ideas['errors']} could not be read" if ideas["errors"] else "") + ".",
                 f"Quantity: {ideas['sizing']}, on {inr(ideas['equity'])} ({ideas['equity_basis']})."]
        if pricey:
            lines.append("Too expensive for this account size (one share > 10% of equity): " + ", ".join(pricey) + ".")
        for b in ideas.get("band_skipped") or []:
            lines.append(f"{b['symbol']}: {b['reason']}.")
        cautions = [i["symbol"] + " (" + i["band_note"] + ")" for i in ideas["ideas"] if i.get("band_note")]
        if cautions:
            lines.append("Caution: " + "; ".join(cautions) + ".")
        if not rows and not pricey:
            lines.append("Nothing passes the screen today.")
        table = {"head": ["Stock", "Price", "Qty", "Cost", "Stop", "6m", "Name"], "rows": rows, "num": [1, 2, 3, 4, 5],
                 # on a phone the company name sits under the symbol instead of squeezing the numbers
                 "html": {"head": ["Stock", "Price", "Qty", "Cost", "Stop", "6m"], "rows": [r[:6] for r in rows],
                          "num": [1, 2, 3, 4, 5], "sub": [r[6] for r in rows]}} if rows else None
        blocks.append(_block(title, lines, table, tone="warn" if wait else None))
    watch = d["watch"]
    if "unavailable" in watch:
        blocks.append(_unavail("Holdings to watch or consider selling", watch))
    else:
        rows = [[i["symbol"], i["source"] + (" (also in practice)" if i.get("also_practice") else ""), inr(i["price"], 2),
                 "; ".join(i["reasons"])] for i in watch["items"]]
        both = " (Groww and practice)" if len(watch.get("places") or []) > 1 else ""
        lines = [f"{watch['checked']} stock{'s' if watch['checked'] != 1 else ''} checked{both}; "
                 f"{watch['healthy']} with nothing to flag."] if watch["checked"] else []
        lines += [f"Note: {n}" for n in watch.get("notes", []) if not n.startswith("Using ")]   # the saved-holdings note is at the top
        if watch.get("more"):
            lines.append(f"and {watch['more']} more not shown.")
        if not watch["items"] and watch["checked"]:
            lines.insert(0, "Nothing to watch today.")
        cards = [{"title": f"{i['symbol']} {inr(i['price'], 2)}",
                  "meta": i["source"] + (" · also in practice" if i.get("also_practice") else ""),
                  "bullets": [r if len(r) <= 90 else r[:87].rstrip() + "..." for r in i["reasons"]]} for i in watch["items"]]
        blocks.append(_block("Holdings to watch or consider selling", lines,
                             {"head": ["Stock", "Where", "Price", "Why"], "rows": rows, "num": [2],
                              "html": {"head": ["Stock", "Price", "Why"], "num": [1], "nowrap": [0, 1],
                                       "rows": [[f"{r[0]} · {r[1]}", r[2], r[3]] for r in rows]}} if rows else None,
                             tone="warn" if rows else None, cards=cards or None))
    blocks.append(_deals_block(d["deals"], "New deals by followed investors"))
    return blocks


def _world_block(w: dict[str, Any]) -> dict[str, Any]:
    if "unavailable" in w:
        return _unavail("World markets", w)
    lines = list(w["region_lines"])
    for key in ("futures_line", "vix_line"):
        if w.get(key):
            lines.append(w[key])
    lines.append(w["note"])
    if w["skipped"]:
        lines.append(f"{w['skipped']} index(es) could not be read and are left out.")
    rows_all = w["us"] + w["asia"] + ([w["vix"]] if w.get("vix") else []) + w["futures"] + w["india"]
    rows = [[r["index"], (num if r["index"] == "Nifty" else num_intl)(r["close"], 2), pct_text(r["d1_pct"]), pct_text(r["d5_pct"]), pct_text(r["d20_pct"]), r["trend"] or ""]
            for r in rows_all]
    table = {"head": ["Index", "Close", "1d", "5d", "20d", "Trend"], "rows": rows, "num": [1, 2, 3, 4],
             # phone: the close sits under the name
             "html": {"head": ["Index", "1d", "5d", "20d", "Trend"], "num": [1, 2, 3], "nowrap": [4], "rows": [r[:1] + r[2:] for r in rows],
                      "sub": [r[1] for r in rows]}} if rows else None
    return _block("World markets", lines, table)


def _gauge_block(g: dict[str, Any]) -> dict[str, Any]:
    if "unavailable" in g:
        return _unavail("Risk gauges", g)
    lines = []
    if g["warnings"]:
        lines.append("⚠ Warning: " + "; ".join(WARN_TEXT.get(w, w) for w in g["warnings"]) + ".")
    lines.append(g["note"])
    lines += [g[k] for k in ("premarket_line", "flows_line", "breadth_line") if g.get(k)]
    if g["skipped"]:
        lines.append(f"{g['skipped']} gauge(s) could not be read and are left out.")
    rows = [[r["gauge"], (num if r["gauge"].startswith("Nifty") else num_intl)(r["value"], 2), pct_text(r["d20_pct"]), pct_text(r["vs_50d_pct"]), r["range"],
             ("⚠ warning: " if r["warning"] else "") + r["reading"]] for r in g["gauges"]]
    table = {"head": ["Gauge", "Value", "20d", "vs 50d avg", "1-year range", "Reading"], "rows": rows, "num": [1, 2, 3],
             "html": {"head": ["Gauge", "Value", "20d"], "num": [1, 2], "rows": [r[:3] for r in rows],
                      "sub": [f"{r[5]}; {r[4]}; {r[3]} vs 50-day" for r in rows]}}
    return _block("Risk gauges", lines, table, tone="bad" if g["warnings"] else None)


def _deals_block(sec: dict[str, Any], title: str) -> dict[str, Any]:
    if "unavailable" in sec:
        return _unavail(title, sec)
    if not sec["deals"]:
        return _block(title, [f"No deals by {', '.join(sec['following'])} since {sec['since']}."])
    rows = [[x["ticker"] + (" (BSE)" if x.get("exchange") == "BSE" else ""), x["transaction"], x["size"], ", ".join(x["who"]) or x["investor"], x["reported"]] for x in sec["deals"]]
    lines = [f"{sec['total']} deal(s) since {sec['since']}" + (f"; the first {len(rows)} are shown." if sec["total"] > len(rows) else ".")]
    return _block(title, lines, {"head": ["Stock", "Deal", "Size", "Who", "Reported"], "rows": rows, "num": []})


def _picture(images: list[dict[str, Any]] | None, cid: str) -> list[dict[str, str]]:
    """The inline picture ``cid`` as a block image, only when it was really made."""
    for i in images or []:
        if i.get("cid") == cid:
            return [{"cid": cid, "alt": str(i.get("alt") or cid)}]
    return []


def _bulletin_blocks(d: dict[str, Any], images: list[dict[str, Any]] | None) -> list[dict[str, Any]]:
    """The market bulletin: Nifty 50 (close, 15-minute chart, text, 4-hour chart, text, levels, indicators, candle),
    global markets, commodities and the concept of the day. A part that is unavailable says so; the rest stays."""
    b = d.get("bulletin")
    if not isinstance(b, dict):
        return []
    blocks: list[dict[str, Any]] = []
    nf = b.get("nifty")
    if isinstance(nf, dict) and "unavailable" in nf:
        blocks.append(_unavail("Market bulletin: Nifty 50", nf))
    elif isinstance(nf, dict):
        L = nf.get("lines") or {}
        head = [L["headline"]] if L.get("headline") else []
        if str(nf.get("session")) != str(d.get("date") or nf.get("session")):
            head.insert(0, f"Figures are for the session of {nf['session']}.")
        blocks.append(_block("Market bulletin: Nifty 50", head, images=_picture(images, "nifty15")))
        mid = [L[k] for k in ("ema", "range") if L.get(k)]
        blocks.append(_block(None, mid, images=_picture(images, "nifty4h"), cont=True))
        rest = [L[k] for k in ("four_hour", "levels", "pivots", "adx", "four_hour_adx", "rsi", "candle") if L.get(k)]
        rest += [f"Note: {n}" for n in nf.get("notes") or []]
        rest.append(b.get("note") or "")
        blocks.append(_block(None, [x for x in rest if x], cont=True))
    g = b.get("global")
    if isinstance(g, dict) and "unavailable" in g:
        blocks.append(_unavail("Global markets", g))
    elif isinstance(g, dict):
        lines = list(g.get("region_lines") or [])
        lines += [x for x in (g.get("futures_line"), g.get("vix_line")) if x]
        lines.append(g.get("note") or "")
        if g.get("skipped"):
            lines.append(f"{g['skipped']} index(es) could not be read and are left out.")
        rows = [[r["market"], num_intl(r["close"], 2), pct_text(r["d1_pct"], 2), r["trend"] or "",
                 (f"{r['why']['title']} ({r['why']['source']})" if r.get("why") else "")] for r in g["markets"]]
        cards = [{"style": "market", "meta": r["line"],
                  "why": (f"In the news: {r['why']['title']} ({r['why']['source']})" if r.get("why") else "")} for r in g["markets"]]
        blocks.append(_block("Global markets", [x for x in lines if x],
                             {"head": ["Market", "Close", "1d", "Trend", "In the news"], "rows": rows, "num": [1, 2]}, cards=cards))
    c = b.get("commodities")
    if isinstance(c, dict) and "unavailable" in c:
        blocks.append(_unavail("Commodities corner", c))
    elif isinstance(c, dict):
        rows = [[r["name"], f"${num_intl(r['last'], 2)}", pct_text(r["d1_pct"], 2), pct_text(r["d5_pct"], 2), r["trend"] or ""]
                for r in c["rows"]]
        lines = [r["reading"] for r in c["rows"]] + [c.get("note") or ""]
        if c.get("skipped"):
            lines.append(f"{c['skipped']} commodity price(s) could not be read and are left out.")
        blocks.append(_block("Commodities corner", [x for x in lines if x],
                             {"head": ["Commodity", "Last", "1d", "5d", "Trend"], "rows": rows, "num": [1, 2, 3],
                              "html": {"head": ["Commodity", "Last", "1d", "5d"], "num": [1, 2, 3], "nowrap": [0],
                                       "rows": [r[:4] for r in rows]}}))
    k = b.get("concept")
    if isinstance(k, dict) and "unavailable" not in k and k.get("title"):
        blocks.append(_block(f"{k.get('label', 'Concept of the day')}: {k['title']}", [k["text"], "Where you see it: " + k["uses"]]))
    return blocks


def _evening_blocks(d: dict[str, Any], images: list[dict[str, Any]] | None = None) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []
    stale = d.get("stale_close")
    if stale:
        why = "No trading today" if stale["reason"] == "no trading today" else "The market has not closed yet"
        blocks.append(_block(None, [f"{why}; figures are from the last close ({stale['label']})."], tone="warn"))
    g = d["groww"]
    if "unavailable" in g:
        blocks.append(_unavail("Your Groww portfolio", g))
    else:
        lines = [f"Value {inr(g['value'])} on {inr(g['invested'])} invested (holdings with a price). "
                 f"Total profit or loss {inr(g['pl'], 0, True)} ({pct_text(g['pl_pct'])})."]
        if not stale:
            if g.get("day_pl") is not None:
                lines.insert(0, f"Today {inr(g['day_pl'], 0, True)} ({pct_text(g['day_pct'])}) against the previous close.")
            else:
                lines.insert(0, "Today's change is unavailable (no previous close).")
        if not stale:
            lines.append("Today's buys appear in your holdings from the next day (T+1 settlement).")
        if g["no_price"]:
            lines.append("Without a market price (bonds or unlisted), not counted: " + ", ".join(g["no_price"]) + ".")
        if g["no_prev_close"] and not stale:
            lines.append("No previous close, left out of today's change: " + ", ".join(g["no_prev_close"]) + ".")
        if stale:
            rows = [[h["symbol"], str(h["qty"]), inr(h["price"], 2), inr(h["pl"], 0, True) if h["pl"] is not None else "n/a",
                     pct_text(h["pl_pct"])] for h in g["holdings"]]
            table = {"head": ["Stock", "Qty", "Price", "Total ₹", "Total %"], "rows": rows, "num": [1, 2, 3, 4]} if rows else None
            tone = None
        else:
            rows = [[h["symbol"], str(h["qty"]), inr(h["price"], 2), pct_text(h["day_pct"]),
                     inr(h["day_pl"], 0, True) if h["day_pl"] is not None else "n/a",
                     inr(h["pl"], 0, True) if h["pl"] is not None else "n/a", pct_text(h["pl_pct"])] for h in g["holdings"]]
            table = {"head": ["Stock", "Qty", "Price", "Today", "Today ₹", "Total ₹", "Total %"], "rows": rows,
                     "num": [1, 2, 3, 4, 5, 6]} if rows else None
            tone = "good" if (g.get("day_pl") or 0) > 0 else "bad" if (g.get("day_pl") or 0) < 0 else None
        blocks.append(_block("Your Groww portfolio", lines, table, tone=tone))
    p = d["practice"]
    if "unavailable" in p:
        blocks.append(_unavail("Practice account", p))
    else:
        total = f"since the start {inr(p['total_pl'], 0, True)} ({pct_text(p['total_pl_pct'])})"
        if p.get("same_as_groww"):
            lines = [f"Practice account holds the same {p['same_as_groww']} stocks as your Groww portfolio (a copy); "
                     f"equity {inr(p['equity'])}, {total}."]
        else:
            lines = [f"Equity {inr(p['equity'])}, cash {inr(p['cash'])}."]
            if not stale:
                lines.append(f"Today {inr(p['day_change'], 0, True)} ({pct_text(p['day_change_pct'])})." if p["day_change"] is not None
                             else (f"No equity point from the previous trading day; since {p['since']}: {inr(p['since_change'], 0, True)} "
                                   f"({pct_text(p['since_change_pct'])})." if p.get("since") else
                                   "Today's change is unavailable (no earlier equity point)."))
            lines.append(total[0].upper() + total[1:] + ".")
        for f in p["stop_fills_today"]:
            lines.append(f"Stop hit today: sold {f['qty']:g} {f['symbol']} at {inr(f['price'], 2)} (stop {inr(f['stop'], 2)}, {f['label']}).")
        if not p["stop_fills_today"] and not stale:
            lines.append("No stop-loss sells today.")
        rows = [[x["symbol"], f"{x['qty']:g}", inr(x["avg"], 2), inr(x["price"], 2) if x["price"] is not None else "n/a",
                 inr(x["pl"], 0, True) if x["pl"] is not None else "n/a", pct_text(x["pl_pct"])] for x in p["positions"]]
        blocks.append(_block("Practice account", lines, {"head": ["Stock", "Qty", "Avg", "Price", "P&L", "P&L %"], "rows": rows,
                                                         "num": [1, 2, 3, 4, 5]} if rows else None))
    blocks += _bulletin_blocks(d, images)
    n = d["news"]
    if "unavailable" in n:
        blocks.append(_unavail("News for your stocks today", n))
    elif not n["items"]:
        blocks.append(_block("News for your stocks today", [n.get("note") or "No tagged headlines for your stocks today."]))
    else:
        rows = [[i["symbol"], i["sentiment"], i["title"], i["source"]] for i in n["items"]]
        lines = ["Headlines are tagged by a language model and can be wrong."]
        if n["total"] > len(rows):
            lines.append(f"{n['total']} headlines; the first {len(rows)} are shown.")
        cards = [{"style": "news", "meta": " · ".join(x for x in (i["symbol"], i["sentiment"], i["source"], i.get("when")) if x),
                  "title": i["title"], "link": i.get("link") or ""} for i in n["items"]]
        blocks.append(_block("News for your stocks today", lines, {"head": ["Stock", "Tone", "Headline", "Source"], "rows": rows, "num": []},
                             cards=cards,
                             tone="warn" if any(i["sentiment"] == "negative" for i in n["items"]) else None))
    blocks.append(_deals_block(d["deals"], "Today's deals by followed investors"))
    return blocks


def document(data: dict[str, Any], summary: str | None = None, writer: str = "none",
             images: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    kind = data["kind"]
    try:
        day = datetime.fromisoformat(data["generated_at"]).strftime("%a %d %b %Y")
    except ValueError:
        day = data.get("date", "")
    head = (f"Today: what to buy and what to watch, {day}" if kind == "morning" else f"Close: your portfolio, {day}")
    blocks = []
    if summary and writer == "rules":
        blocks.append(_block("In short (written by the rules)", [summary]))
    elif summary:   # a model wrote it: say which, and to check the numbers
        who = "Claude Haiku" if "claude-haiku" in writer else writer
        blocks.append(_block(f"In short (written by {who} — check the numbers below)", [summary]))
    saved = None
    if kind == "evening" and isinstance(data.get("groww"), dict):
        saved = data["groww"].get("saved")
    elif kind == "morning" and isinstance(data.get("watch"), dict):
        saved = next((n[len("Using "):] for n in data["watch"].get("notes", []) if n.startswith("Using ")), None)
    if saved:
        blocks.append(_block(None, ["Using " + saved + "."], tone="warn"))
    blocks += _morning_blocks(data) if kind == "morning" else _evening_blocks(data, images)
    foot = [FOOTER] + ([DELAYED] if data.get("delayed") else [])
    return {"title": head, "blocks": blocks, "footer": foot}


# -- plain text ---------------------------------------------------------------------------
def _text_table(t: dict[str, Any]) -> list[str]:
    head, rows, num = t["head"], t["rows"], set(t.get("num") or [])
    # Why / Headline columns come last and are not padded
    widths = [max(len(str(r[i])) for r in [head] + rows) for i in range(len(head))]
    out = []
    for r in [head] + rows:
        cells = []
        for i, c in enumerate(r):
            c = str(c)
            if i == len(r) - 1 and i not in num:
                cells.append(c)
            else:
                cells.append(c.rjust(widths[i]) if i in num else c.ljust(widths[i]))
        out.append("  " + "  ".join(cells))
    return out


def to_text(doc: dict[str, Any]) -> str:
    out = [doc["title"], "=" * len(doc["title"]), ""]
    for b in doc["blocks"]:
        head, sep, tail = (b["title"] or "").partition(" (")   # "IN SHORT (written by ...)": only the name is upper-cased
        if b["title"] is None and b.get("cont") and out and out[-1] == "":
            out.pop()   # a continuation of the block above: no blank line, no heading
        if b["title"] is not None or not b.get("cont"):
            out.append(head.upper() + sep + tail)
        out += [f"{k}: {v}" for k, v in b.get("kv") or []]
        out += b["lines"]
        out += [f"[Chart: {i['alt']}]" for i in b.get("images") or []]
        if b["table"]:
            out += _text_table(b["table"])
        out.append("")
    out += doc["footer"]
    return "\n".join(out) + "\n"


# -- HTML -------------------------------------------------------------------------------------
def _e(x: object) -> str:
    return _html.escape(str(x), quote=True)


def to_html(doc: dict[str, Any]) -> str:
    font = "font-family:Arial,Helvetica,sans-serif;"
    parts = [f'<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;{font}">'
             '<tr><td align="center" style="padding:16px">'
             '<table role="presentation" cellpadding="0" cellspacing="0" '
             'style="max-width:640px;width:100%;background:#ffffff;border:1px solid #e5e7eb">'
             f'<tr><td style="padding:16px 20px;background:#111827;color:#ffffff;font-size:18px;font-weight:bold;{font}">{_e(doc["title"])}</td></tr>']
    for b in doc["blocks"]:
        colour = TONES.get(b["tone"], TONES[None])
        parts.append(f'<tr><td style="padding:{4 if b.get("cont") else 14}px 20px 4px 20px;{font}">')
        if b["title"]:
            parts.append(f'<div style="font-size:15px;font-weight:bold;color:{colour};border-bottom:1px solid #e5e7eb;padding-bottom:4px">{_e(b["title"])}</div>')
        for line in b["lines"]:
            parts.append(f'<div style="font-size:14px;color:#111827;line-height:1.45;padding-top:6px">{_e(line)}</div>')
        for img in b.get("images") or []:   # inline picture attached to the email (content id), or a data: URL in the preview
            parts.append(f'<img src="cid:{_e(img["cid"])}" alt="{_e(img["alt"])}" width="600" '
                         'style="display:block;width:100%;max-width:600px;height:auto;border:0;margin-top:8px">')
        if b.get("kv"):
            parts.append('<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:6px;border-collapse:collapse;width:100%">')
            for k, v in b["kv"]:
                parts.append(f'<tr><td style="font-size:12px;color:#6b7280;padding:2px 8px 2px 0;vertical-align:top;white-space:nowrap">{_e(k)}</td>'
                             f'<td style="font-size:13px;color:#111827;padding:2px 0">{_e(v)}</td></tr>')
            parts.append("</table>")
        t = None if b.get("cards") else b["table"]   # the watch list is cards on a phone, not a table
        for card in b.get("cards") or []:
            if card.get("style") == "market":   # the index line, then the headline that names it (if any) in small type
                why = (f'<div style="font-size:11px;color:#6b7280;line-height:1.35">{_e(card["why"])}</div>' if card.get("why") else "")
                parts.append(f'<div style="margin-top:7px"><div style="font-size:13px;color:#111827">{_e(card["meta"])}</div>{why}</div>')
                continue
            if card.get("style") == "news":   # small muted line, then the headline at full width (linked when it has a link)
                head = _e(card["title"])
                if str(card.get("link") or "").startswith(("http://", "https://")):
                    head = f'<a href="{_e(card["link"])}" style="color:#1d4ed8;text-decoration:none">{head}</a>'
                parts.append(f'<div style="margin-top:9px"><div style="font-size:11px;color:#6b7280">{_e(card["meta"])}</div>'
                             f'<div style="font-size:13px;color:#111827;line-height:1.4">{head}</div></div>')
                continue
            parts.append(f'<div style="margin-top:10px"><span style="font-size:14px;font-weight:bold;color:#111827">{_e(card["title"])}</span> '
                         f'<span style="font-size:11px;color:#6b7280">{_e(card["meta"])}</span>'
                         '<ul style="margin:3px 0 0 18px;padding:0">'
                         + "".join(f'<li style="font-size:13px;color:#111827;line-height:1.4">{_e(x)}</li>' for x in card["bullets"])
                         + "</ul></div>")
        if t:
            t = t.get("html") or t     # the phone layout may differ from the text one
            num, nowrap, sub = set(t.get("num") or []), set(t.get("nowrap") or []), t.get("sub")
            parts.append('<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border-collapse:collapse;width:100%">')
            parts.append("<tr>" + "".join(
                f'<th align="{"right" if i in num else "left"}" style="font-size:12px;color:#6b7280;padding:4px 6px;border-bottom:1px solid #e5e7eb">{_e(h)}</th>'
                for i, h in enumerate(t["head"])) + "</tr>")
            for n, r in enumerate(t["rows"]):
                cells = []
                for i, c in enumerate(r):
                    style = "font-size:13px;color:#111827;padding:4px 6px;border-bottom:1px solid #f3f4f6;vertical-align:top;"
                    if i in num or i in nowrap:
                        style += "white-space:nowrap;"
                    extra = ""
                    if i == 0 and sub and sub[n]:
                        extra = f'<div style="font-size:11px;color:#6b7280;white-space:normal">{_e(sub[n])}</div>'
                    cells.append(f'<td align="{"right" if i in num else "left"}" style="{style}">{_e(c)}{extra}</td>')
                parts.append("<tr>" + "".join(cells) + "</tr>")
            parts.append("</table>")
        parts.append("</td></tr>")
    foot = "<br>".join(_e(x) for x in doc["footer"])
    parts.append(f'<tr><td style="padding:16px 20px;font-size:12px;color:#6b7280;{font}">{foot}</td></tr></table></td></tr></table>')
    return "".join(parts)


def strip_chart_mentions(text: str) -> str:
    """The text part without its "[Chart: ...]" lines (when the pictures are not sent)."""
    return re.sub(r"(?m)^\[Chart: .*\]\n", "", text)


def strip_cid_images(html: str) -> str:
    """The HTML without its inline pictures (when they cannot be sent)."""
    return re.sub(r"<img\b[^>]*\bsrc=\"cid:[^\"]*\"[^>]*>", "", html)


def inline_data_urls(html: str, images: list[dict[str, Any]] | None) -> str:
    """The HTML with each ``cid:`` picture replaced by a data: URL, for a browser or the dashboard preview."""
    for i in images or []:
        url = "data:image/png;base64," + base64.b64encode(i["content"]).decode("ascii")
        html = html.replace(f'src="cid:{i["cid"]}"', f'src="{url}"')
    return html


def render(data: dict[str, Any], summary: str | None = None, writer: str = "none",
           images: list[dict[str, Any]] | None = None) -> dict[str, str]:
    doc = document(data, summary, writer, images)
    return {"subject": subject(data), "text": to_text(doc), "html": to_html(doc)}
