"""Turn the digest data into an email: subject, plain text and a simple inline-styled HTML table layout.

Both renderers work from one small document (a list of blocks), so the text and the HTML always say the same thing.
Everything that goes into the HTML is escaped; the subject goes through ``clean_text``.
"""

from __future__ import annotations

import html as _html
from datetime import datetime
from typing import Any

from .digest import WARN_TEXT, inr, num, pct_text
from .notify import clean_text

FOOTER = "Generated by rules from public data; not financial advice. The agent places no orders from this email."
DELAYED = "(prices may be delayed)"
TONES = {"warn": "#b45309", "bad": "#b91c1c", "good": "#15803d", None: "#111827"}


def _plural(n: int, word: str) -> str:
    return f"{n} {word}" if n == 1 else f"{n} {word}s"


def subject(data: dict[str, Any]) -> str:
    if data["kind"] == "morning":
        mood = data.get("mood") or {}
        label = "market data unavailable" if "unavailable" in mood else str(mood.get("regime") or "unknown").replace("_", "-")
        ideas = data.get("buy_ideas") or {}
        n_buy = 0 if ("unavailable" in ideas or ideas.get("wait")) else len(ideas.get("ideas", []))
        watch = data.get("watch") or {}
        n_watch = 0 if "unavailable" in watch else watch.get("total", len(watch.get("items", [])))
        s = f"Today: {label} · {_plural(n_buy, 'buy idea')} · {n_watch} to watch"
    else:
        g, p = data.get("groww") or {}, data.get("practice") or {}
        if "unavailable" not in g:
            day = (f"{inr(g.get('day_pl'), 0, True)} / {pct_text(g.get('day_pct'))} today"
                   if g.get("day_pl") is not None else "day change unavailable")
            s = f"Close: {day} · total {inr(g.get('pl'), 0, True)} ({pct_text(g.get('pl_pct'))})"
        elif "unavailable" not in p:
            day = (f"{inr(p.get('day_change'), 0, True)} / {pct_text(p.get('day_change_pct'))} today"
                   if p.get("day_change") is not None else "day change unavailable")
            s = f"Close: practice {day} · total {inr(p.get('total_pl'), 0, True)} ({pct_text(p.get('total_pl_pct'))})"
        else:
            s = "Close: portfolio unavailable"
    return clean_text(s, 150)


def _block(title: str | None, lines: list[str] | None = None, table: dict[str, Any] | None = None,
           tone: str | None = None) -> dict[str, Any]:
    return {"title": title, "lines": lines or [], "table": table, "tone": tone}


def _unavail(title: str, sec: dict[str, Any]) -> dict[str, Any]:
    return _block(title, [f"Unavailable: {sec['unavailable']}"], tone="warn")


def _morning_blocks(d: dict[str, Any]) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []
    mood = d["mood"]
    if "unavailable" in mood:
        blocks.append(_unavail("Market mood", mood))
    else:
        lines = [mood["summary"] or str(mood["regime"]).replace("_", "-")]
        if mood.get("no_new_buys"):
            lines.insert(0, "No new buys today: " + " and ".join(mood.get("why") or ["the market filter says wait"]) + ".")
            lines.insert(1, "Rule: " + (mood.get("rules") or "the market filter") + ".")
        lines += [f"Note: {n}" for n in mood.get("notes", [])]
        blocks.append(_block("Market mood", lines, tone="bad" if mood.get("no_new_buys") else None))
    if "world" in d:
        blocks.append(_world_block(d["world"]))
    if "gauges" in d:
        blocks.append(_gauge_block(d["gauges"]))
    ideas = d["buy_ideas"]
    wait = (not ("unavailable" in mood)) and mood.get("no_new_buys")
    title = "Would pass, but the market filter says wait" if wait else "Buy ideas"
    if "unavailable" in ideas:
        blocks.append(_unavail(title, ideas))
    else:
        rows = [[i["symbol"], inr(i["price"], 2), str(i["qty"]), inr(i["notional"]), inr(i["stop"], 2) if i["stop"] else "n/a",
                 pct_text(i["ret_6m_pct"]), i["name"]] for i in ideas["ideas"]]
        pricey = ideas.get("too_expensive") or []
        lines = [f"Momentum screen of {ideas['universe']}: {ideas['scored']} of {ideas['universe_size']} scored, "
                 f"{ideas['eligible']} pass (above the 200-day average, liquid)"
                 + (f"; {ideas['errors']} could not be read" if ideas["errors"] else "") + ".",
                 f"Quantity: {ideas['sizing']}, on {inr(ideas['equity'])} ({ideas['equity_basis']})."]
        if pricey:
            lines.append("Too expensive for this account size (one share > 10% of equity): " + ", ".join(pricey) + ".")
        if not rows and not pricey:
            lines.append("Nothing passes the screen today.")
        table = {"head": ["Stock", "Price", "Qty", "Cost", "Stop", "6m", "Name"], "rows": rows, "num": [1, 2, 3, 4, 5],
                 # on a phone the company name sits under the symbol instead of squeezing the numbers
                 "html": {"head": ["Stock", "Price", "Qty", "Cost", "Stop", "6m"], "rows": [r[:6] for r in rows],
                          "num": [1, 2, 3, 4, 5], "sub": [r[6] for r in rows]}} if rows else None
        blocks.append(_block(title, lines, table, tone="warn" if wait else None))
    watch = d["watch"]
    if "unavailable" in watch:
        blocks.append(_unavail("Holdings to watch or consider selling", watch))
    else:
        rows = [[i["symbol"], i["source"] + (" (also in practice)" if i.get("also_practice") else ""), inr(i["price"], 2),
                 "; ".join(i["reasons"])] for i in watch["items"]]
        lines = [f"{watch['checked']} holdings checked; {watch['healthy']} with nothing to flag."] if watch["checked"] else []
        lines += [f"Note: {n}" for n in watch.get("notes", [])]
        if watch.get("more"):
            lines.append(f"and {watch['more']} more not shown.")
        if not watch["items"] and watch["checked"]:
            lines.insert(0, "Nothing to watch today.")
        blocks.append(_block("Holdings to watch or consider selling", lines,
                             {"head": ["Stock", "Where", "Price", "Why"], "rows": rows, "num": [2],
                              "html": {"head": ["Stock", "Price", "Why"], "num": [1], "nowrap": [0, 1],
                                       "rows": [[f"{r[0]} · {r[1]}", r[2], r[3]] for r in rows]}} if rows else None,
                             tone="warn" if rows else None))
    blocks.append(_deals_block(d["deals"], "New deals by followed investors"))
    return blocks


def _world_block(w: dict[str, Any]) -> dict[str, Any]:
    if "unavailable" in w:
        return _unavail("World markets", w)
    lines = list(w["region_lines"])
    for key in ("futures_line", "vix_line"):
        if w.get(key):
            lines.append(w[key])
    lines.append(w["note"])
    if w["skipped"]:
        lines.append(f"{w['skipped']} index(es) could not be read and are left out.")
    rows_all = w["us"] + w["asia"] + ([w["vix"]] if w.get("vix") else []) + w["futures"] + w["india"]
    rows = [[r["index"], num(r["close"], 2), pct_text(r["d1_pct"]), pct_text(r["d5_pct"]), pct_text(r["d20_pct"]), r["trend"] or ""]
            for r in rows_all]
    table = {"head": ["Index", "Close", "1d", "5d", "20d", "Trend"], "rows": rows, "num": [1, 2, 3, 4],
             # phone: the close sits under the name
             "html": {"head": ["Index", "1d", "5d", "20d", "Trend"], "num": [1, 2, 3], "nowrap": [4], "rows": [r[:1] + r[2:] for r in rows],
                      "sub": [r[1] for r in rows]}} if rows else None
    return _block("World markets", lines, table)


def _gauge_block(g: dict[str, Any]) -> dict[str, Any]:
    if "unavailable" in g:
        return _unavail("Risk gauges", g)
    lines = []
    if g["warnings"]:
        lines.append("⚠ Warning: " + "; ".join(WARN_TEXT.get(w, w) for w in g["warnings"]) + ".")
    lines.append(g["note"])
    if g["skipped"]:
        lines.append(f"{g['skipped']} gauge(s) could not be read and are left out.")
    rows = [[r["gauge"], num(r["value"], 2), pct_text(r["d20_pct"]), pct_text(r["vs_50d_pct"]), r["range"],
             ("⚠ warning: " if r["warning"] else "") + r["reading"]] for r in g["gauges"]]
    table = {"head": ["Gauge", "Value", "20d", "vs 50d avg", "1-year range", "Reading"], "rows": rows, "num": [1, 2, 3],
             "html": {"head": ["Gauge", "Value", "20d"], "num": [1, 2], "rows": [r[:3] for r in rows],
                      "sub": [f"{r[5]}; {r[4]}; {r[3]} vs 50-day" for r in rows]}}
    return _block("Risk gauges", lines, table, tone="bad" if g["warnings"] else None)


def _deals_block(sec: dict[str, Any], title: str) -> dict[str, Any]:
    if "unavailable" in sec:
        return _unavail(title, sec)
    if not sec["deals"]:
        return _block(title, [f"No deals by {', '.join(sec['following'])} since {sec['since']}."])
    rows = [[x["ticker"], x["transaction"], x["size"], ", ".join(x["who"]) or x["investor"], x["reported"]] for x in sec["deals"]]
    lines = [f"{sec['total']} deal(s) since {sec['since']}" + (f"; the first {len(rows)} are shown." if sec["total"] > len(rows) else ".")]
    return _block(title, lines, {"head": ["Stock", "Deal", "Size", "Who", "Reported"], "rows": rows, "num": []})


def _evening_blocks(d: dict[str, Any]) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []
    g = d["groww"]
    if "unavailable" in g:
        blocks.append(_unavail("Your Groww portfolio", g))
    else:
        lines = [f"Value {inr(g['value'])} on {inr(g['invested'])} invested (holdings with a price). "
                 f"Total profit or loss {inr(g['pl'], 0, True)} ({pct_text(g['pl_pct'])})."]
        if g.get("day_pl") is not None:
            lines.insert(0, f"Today {inr(g['day_pl'], 0, True)} ({pct_text(g['day_pct'])}) against the previous close.")
        else:
            lines.insert(0, "Today's change is unavailable (no previous close).")
        if g.get("saved"):
            lines.insert(0, "Using " + g["saved"] + ".")
        lines.append("Today's buys appear in your holdings from the next day (T+1 settlement).")
        if g["no_price"]:
            lines.append("Without a market price (bonds or unlisted), not counted: " + ", ".join(g["no_price"]) + ".")
        if g["no_prev_close"]:
            lines.append("No previous close, left out of today's change: " + ", ".join(g["no_prev_close"]) + ".")
        rows = [[h["symbol"], str(h["qty"]), inr(h["price"], 2), pct_text(h["day_pct"]), inr(h["day_pl"], 0, True) if h["day_pl"] is not None else "n/a",
                 inr(h["pl"], 0, True) if h["pl"] is not None else "n/a", pct_text(h["pl_pct"])] for h in g["holdings"]]
        blocks.append(_block("Your Groww portfolio", lines, {
            "head": ["Stock", "Qty", "Price", "Today", "Today ₹", "Total ₹", "Total %"], "rows": rows, "num": [1, 2, 3, 4, 5, 6]} if rows else None,
            tone="good" if (g.get("day_pl") or 0) > 0 else "bad" if (g.get("day_pl") or 0) < 0 else None))
    p = d["practice"]
    if "unavailable" in p:
        blocks.append(_unavail("Practice account", p))
    else:
        lines = [f"Equity {inr(p['equity'])}, cash {inr(p['cash'])}.",
                 (f"Today {inr(p['day_change'], 0, True)} ({pct_text(p['day_change_pct'])})." if p["day_change"] is not None
                  else (f"No equity point from the previous trading day; since {p['since']}: {inr(p['since_change'], 0, True)} "
                        f"({pct_text(p['since_change_pct'])})." if p.get("since") else
                        "Today's change is unavailable (no earlier equity point).")),
                 f"Since the start {inr(p['total_pl'], 0, True)} ({pct_text(p['total_pl_pct'])})."]
        for f in p["stop_fills_today"]:
            lines.append(f"Stop hit today: sold {f['qty']:g} {f['symbol']} at {inr(f['price'], 2)} (stop {inr(f['stop'], 2)}, {f['label']}).")
        if not p["stop_fills_today"]:
            lines.append("No stop-loss sells today.")
        rows = [[x["symbol"], f"{x['qty']:g}", inr(x["avg"], 2), inr(x["price"], 2) if x["price"] is not None else "n/a",
                 inr(x["pl"], 0, True) if x["pl"] is not None else "n/a", pct_text(x["pl_pct"])] for x in p["positions"]]
        blocks.append(_block("Practice account", lines, {"head": ["Stock", "Qty", "Avg", "Price", "P&L", "P&L %"], "rows": rows,
                                                         "num": [1, 2, 3, 4, 5]} if rows else None))
    n = d["news"]
    if "unavailable" in n:
        blocks.append(_unavail("News for your stocks today", n))
    elif not n["items"]:
        blocks.append(_block("News for your stocks today", [n.get("note") or "No tagged headlines for your stocks today."]))
    else:
        rows = [[i["symbol"], i["sentiment"], i["title"], i["source"]] for i in n["items"]]
        lines = ["Headlines are tagged by a language model and can be wrong."]
        if n["total"] > len(rows):
            lines.append(f"{n['total']} headlines; the first {len(rows)} are shown.")
        blocks.append(_block("News for your stocks today", lines, {"head": ["Stock", "Tone", "Headline", "Source"], "rows": rows, "num": []},
                             tone="warn" if any(i["sentiment"] == "negative" for i in n["items"]) else None))
    blocks.append(_deals_block(d["deals"], "Today's deals by followed investors"))
    return blocks


def document(data: dict[str, Any], summary: str | None = None, writer: str = "none") -> dict[str, Any]:
    kind = data["kind"]
    try:
        day = datetime.fromisoformat(data["generated_at"]).strftime("%a %d %b %Y")
    except ValueError:
        day = data.get("date", "")
    head = (f"Today: what to buy and what to watch, {day}" if kind == "morning" else f"Close: your portfolio, {day}")
    blocks = []
    if summary:
        blocks.append(_block("Summary", [summary, f"Summary written by {writer} — check the numbers below."]))
    blocks += _morning_blocks(data) if kind == "morning" else _evening_blocks(data)
    foot = [FOOTER] + ([DELAYED] if data.get("delayed") else [])
    return {"title": head, "blocks": blocks, "footer": foot}


# -- plain text ---------------------------------------------------------------------------
def _text_table(t: dict[str, Any]) -> list[str]:
    head, rows, num = t["head"], t["rows"], set(t.get("num") or [])
    # Why / Headline columns come last and are not padded
    widths = [max(len(str(r[i])) for r in [head] + rows) for i in range(len(head))]
    out = []
    for r in [head] + rows:
        cells = []
        for i, c in enumerate(r):
            c = str(c)
            if i == len(r) - 1 and i not in num:
                cells.append(c)
            else:
                cells.append(c.rjust(widths[i]) if i in num else c.ljust(widths[i]))
        out.append("  " + "  ".join(cells))
    return out


def to_text(doc: dict[str, Any]) -> str:
    out = [doc["title"], "=" * len(doc["title"]), ""]
    for b in doc["blocks"]:
        out.append(b["title"].upper() if b["title"] else "")
        out += b["lines"]
        if b["table"]:
            out += _text_table(b["table"])
        out.append("")
    out += doc["footer"]
    return "\n".join(out) + "\n"


# -- HTML -------------------------------------------------------------------------------------
def _e(x: object) -> str:
    return _html.escape(str(x), quote=True)


def to_html(doc: dict[str, Any]) -> str:
    font = "font-family:Arial,Helvetica,sans-serif;"
    parts = [f'<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;{font}">'
             '<tr><td align="center" style="padding:16px">'
             '<table role="presentation" cellpadding="0" cellspacing="0" '
             'style="max-width:640px;width:100%;background:#ffffff;border:1px solid #e5e7eb">'
             f'<tr><td style="padding:16px 20px;background:#111827;color:#ffffff;font-size:18px;font-weight:bold;{font}">{_e(doc["title"])}</td></tr>']
    for b in doc["blocks"]:
        colour = TONES.get(b["tone"], TONES[None])
        parts.append(f'<tr><td style="padding:14px 20px 4px 20px;{font}">')
        if b["title"]:
            parts.append(f'<div style="font-size:15px;font-weight:bold;color:{colour};border-bottom:1px solid #e5e7eb;padding-bottom:4px">{_e(b["title"])}</div>')
        for line in b["lines"]:
            parts.append(f'<div style="font-size:14px;color:#111827;line-height:1.45;padding-top:6px">{_e(line)}</div>')
        t = b["table"]
        if t:
            t = t.get("html") or t     # the phone layout may differ from the text one
            num, nowrap, sub = set(t.get("num") or []), set(t.get("nowrap") or []), t.get("sub")
            parts.append('<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:8px;border-collapse:collapse;width:100%">')
            parts.append("<tr>" + "".join(
                f'<th align="{"right" if i in num else "left"}" style="font-size:12px;color:#6b7280;padding:4px 6px;border-bottom:1px solid #e5e7eb">{_e(h)}</th>'
                for i, h in enumerate(t["head"])) + "</tr>")
            for n, r in enumerate(t["rows"]):
                cells = []
                for i, c in enumerate(r):
                    style = "font-size:13px;color:#111827;padding:4px 6px;border-bottom:1px solid #f3f4f6;vertical-align:top;"
                    if i in num or i in nowrap:
                        style += "white-space:nowrap;"
                    extra = ""
                    if i == 0 and sub and sub[n]:
                        extra = f'<div style="font-size:11px;color:#6b7280;white-space:normal">{_e(sub[n])}</div>'
                    cells.append(f'<td align="{"right" if i in num else "left"}" style="{style}">{_e(c)}{extra}</td>')
                parts.append("<tr>" + "".join(cells) + "</tr>")
            parts.append("</table>")
        parts.append("</td></tr>")
    foot = "<br>".join(_e(x) for x in doc["footer"])
    parts.append(f'<tr><td style="padding:16px 20px;font-size:12px;color:#6b7280;{font}">{foot}</td></tr></table></td></tr></table>')
    return "".join(parts)


def render(data: dict[str, Any], summary: str | None = None, writer: str = "none") -> dict[str, str]:
    doc = document(data, summary, writer)
    return {"subject": subject(data), "text": to_text(doc), "html": to_html(doc)}
